#!/bin/sh -u
exec 2>&1
. /etc/runit/functions

msg 'starting...'

VAR=$(jq '.wizard.miyagi_cloud_conn' /mnt/flash/sw-config.json)

while [ "$VAR" != "true"]; do
    sleep 60
    VAR=$(jq '.wizard.miyagi_cloud_conn' /mnt/flash/sw-config.json)
done

msg 'starting live logs...'
exec live_log
