#!/bin/sh

. /etc/rc.conf
CURRENT_SR_NUM=$(grep '0x1004' "$REGISTRY_FILE" 2>/dev/null | cut -d'=' -f2 | tr -d ' .<>*\\/\t')
MODEL_NUM=$(rc_get_agent_model_hwrev)
# MODEL_NUM="QN-CS-241GF"
PKT_BUFFER=/mnt/flash/external/persistent/pkt_buffer

_SECOND_PRECIOUS_MODEL=$(echo "$MODEL_NUM" | awk -F '-' '{print $2}')
_THIRD_PRECIOUS_MODEL=$(echo "$MODEL_NUM" | awk -F '-' '{print $3}')
echo $_SECOND_PRECIOUS_MODEL
echo $_THIRD_PRECIOUS_MODEL

if [ "$_THIRD_PRECIOUS_MODEL" = "225" ] || [ "$_THIRD_PRECIOUS_MODEL" = "230" ] || [ "$_SECOND_PRECIOUS_MODEL" = "IS" ]; then
    # echo "3 MB" > $PKT_BUFFER
    echo "3 MB"

elif [ "$_THIRD_PRECIOUS_MODEL" = "335" ] || [ "$_THIRD_PRECIOUS_MODEL" = "330" ]; then
    # echo "6 MB" > $PKT_BUFFER
    echo "6 MB"

elif [ "$_THIRD_PRECIOUS_MODEL" = "425" ] || [ "$_THIRD_PRECIOUS_MODEL" = "435" ] || [ "$_THIRD_PRECIOUS_MODEL" = "241GF" ]; then
    # echo "8 MB" > $PKT_BUFFER
    echo "8 MB"

elif [ "$_SECOND_PRECIOUS_MODEL" = "CS" ]; then
    # echo "8 MB" > $PKT_BUFFER
    echo "24 MB"

elif [ "$_SECOND_PRECIOUS_MODEL" = "DS" ]; then
    # echo "8 MB" > $PKT_BUFFER
    echo "64 MB"

fi
