#!/bin/sh -u
exec 2>&1
. /etc/runit/functions

msg 'executing General service...'

IP="203.0.113.121"
while ! ping -c 1 -W 1 "$IP" >/dev/null; do
    sleep 2
done

exec /usr/bin/set_hostname &

while true; do
    exec /usr/bin/user_sync &
    sleep 5
done

