#!/bin/sh -u
exec 2>&1
. /etc/runit/functions

msg 'executing General service...'

IP="203.0.113.121"
while ! ping -c 1 -W 1 "$IP" >/dev/null; do
    sleep 2
done

# Using a portable for loop
i=1
while [ "$i" -le 5 ]; do
    /usr/bin/set_hostname
    i=$((i + 1))
    sleep 2  # Optional: Add a delay between iterations
done

while true; do
    /usr/bin/user_sync &
    sleep 5
done
